### ISSUE TITLE
It doesn't allow me to print the content in a modal pop up, always gets whole screen. Not only the  modal pop up. Ctrl+p or window.print()

### ISSUE THREAD

**Issue by darshanawollstra** [a-x-/react-easy-print#10]

**Comment by a-x-** [comment]
Hey,
Sorry for the delay!
Can you provide some code?

**Comment by darshanawollstra** [comment]
got resolved it by adding all the printable things inside a div element and by using another printing component i was able to get the modal  pop up to a whole printing page.
