### ISSUE TITLE
Images Not Appearing

### ISSUE THREAD

**Issue by darshanawollstra** [a-x-/react-easy-print#27]
In my wep page, all the relevant  images are displayed. Once i get the page  to print preview mode, it doesn't show the images (broken images). Could anybody help me on this?

**Comment by a-x-** [comment]
Hey, @darshanawollstra 
I'll try help you

Are you use v0.6.0-beta?
Can you show some screenshots and little code snippets?

**Comment by darshanawollstra** [comment]
![screenshot from 2018-06-25 10-04-48](https://user-images.githubusercontent.com/32511059/41830548-5f294700-785f-11e8-88c3-d752af7995c7.png)
 Images taken from the web sites are not displayed. I'm using react-to-print 1.0.16 version

**Comment by darshanawollstra** [comment]
got it solved by adding the image as a backgroundImage  for a div element.
