### ISSUE TITLE
missing dependency on load-styles

### ISSUE THREAD

**Issue by tiodan81** [a-x-/react-easy-print#28]
Using the PrintProvider, Print, or NoPrint components all throw errors like

```
ERROR in ./node_modules/react-easy-print/lib/es/PrintProvider.js
Module not found: Error: Can't resolve 'load-styles' in '/node_modules/react-easy-print/lib/es'
```

resolved by manually installing `load-styles`

**Comment by a-x-** [comment]
Thank you, @tiodan81! It's weird how we missed it while testing on our services 🤔
📦 0.6.0-beta.1
