### ISSUE TITLE
avoid re-render onPrint

### ISSUE THREAD

**Issue by a-x-** [a-x-/react-easy-print#4]
Bug: lost every component's state on print 

TODO
- Render tmp view into separate root.
- Place tmp root as fixed 0:0
- Don't touch main react root.

**Comment by a-x-** [comment]
Wow
Use React16 portals 
https://hackernoon.com/using-a-react-16-portal-to-do-something-cool-2a2d627b0202?source=linkShare-c20285a847ce-1510861015

Don’t forget about Fall back

**Comment by kevindekemele** [comment]
Hello, so far your package has done good work for me, but indeed the state is lost.
What do you mean exactly by using the portals?

Do I need  to wrap a component which I use to portal with <Print>?

**Comment by Serjobas** [comment]
API will be the same,
we'll be using `ReactDOM.createPortal` under the hood

**Comment by a-x-** [comment]
📦 0.7.1-0
