### ISSUE TITLE
ts and ssr

### ISSUE THREAD

**Issue by a-x-** [a-x-/react-easy-print#7]
Hey, @wealth 🙌

Do you want propose your changes back?
https://github.com/wealth/react-easy-print/commit/c2185c93a39cafabf5dc13bc210d43d0cbdab990

I'm ready to accept

**Comment by wealth** [comment]
Hi, im not using it currently, but here's pull request https://github.com/a-x-/react-easy-print/pull/8

**Comment by a-x-** [comment]
Thank you,

I'm gonna format it and remove `global.window`

**Comment by a-x-** [comment]
Can you describe what `global.window` is? :)

Browsers does not contain the `global` object

**Comment by wealth** [comment]
I'm not sure :), but i think global.window is a window object in node SSR env. If you write just window, it'll be undeclared variable.

**Comment by a-x-** [comment]
ok, so i'll rewrite it like this for compatibiliti with both node ssr and browsers enviroments:
`typeof global !== 'undefined' ? global.window : window`

**Comment by a-x-** [comment]
we added ts typings.
I created separate SSR issue
If you can propose SSR and none SSR ready code, we'll be happy merge it.

**Comment by a-x-** [comment]
📦 0.7.1-0

**Comment by inspirecharles** [comment]
Hi, was this already fixed for ssr?
I want to implement this package
